const generateYearOptions = (startYear, endYear) => {
  const years = [];
  for (let year = endYear; year >= startYear; year--) {
    years.push({ id: year.toString(), label: year.toString() });
  }
  return years;
};

const startYear = 1980;
const currentYear = new Date().getFullYear();
const yearOptions = generateYearOptions(startYear, currentYear);

export const basicCarFormControls = [
  {
    label: "Model",
    name: "model",
    componentType: "select",
    options: [
      { id: "corolla", label: "Corolla" },
      { id: "camry", label: "Camry" },
      { id: "rav4", label: "RAV4" },
      { id: "hilux", label: "Hilux" },
      { id: "civic", label: "Civic" },
      { id: "accord", label: "Accord" },
      { id: "cr-v", label: "CR-V" },
      { id: "fit", label: "Fit" },
      { id: "mustang", label: "Mustang" },
      { id: "f150", label: "F-150" },
      { id: "explorer", label: "Explorer" },
      { id: "altima", label: "Altima" },
      { id: "sentra", label: "Sentra" },
      { id: "rogue", label: "Rogue" },
      { id: "pathfinder", label: "Pathfinder" },
      { id: "tucson", label: "Tucson" },
      { id: "sonata", label: "Sonata" },
      { id: "elantra", label: "Elantra" },
      { id: "cx-5", label: "CX-5" },
      { id: "mazda3", label: "Mazda3" },
      { id: "impreza", label: "Impreza" },
      { id: "forester", label: "Forester" },
      { id: "outback", label: "Outback" },
      { id: "es350", label: "ES 350" },
      { id: "rx350", label: "RX 350" },
      { id: "lx570", label: "LX 570" },
      { id: "3-series", label: "3 Series" },
      { id: "5-series", label: "5 Series" },
      { id: "x5", label: "X5" },
      { id: "a4", label: "A4" },
      { id: "q5", label: "Q5" },
      { id: "q7", label: "Q7" },
      { id: "c-class", label: "C-Class" },
      { id: "e-class", label: "E-Class" },
      { id: "gle", label: "GLE" },
      { id: "911", label: "911" },
      { id: "cayenne", label: "Cayenne" },
      { id: "macan", label: "Macan" },
      { id: "cherokee", label: "Cherokee" },
      { id: "wrangler", label: "Wrangler" },
      { id: "compass", label: "Compass" },
      { id: "model-s", label: "Model S" },
      { id: "model-3", label: "Model 3" },
      { id: "model-x", label: "Model X" },
      { id: "model-y", label: "Model Y" },
      { id: "range-rover", label: "Range Rover" },
      { id: "defender", label: "Defender" },
      { id: "discovery", label: "Discovery" },
    ],
  },
  {
    label: "Make",
    name: "make",
    componentType: "select",
    options: [
      { id: "hyundai", label: "HYUNDAI" },
      { id: "kia", label: "KIA" },
      { id: "nissan", label: "NISSAN" },
      { id: "isuzu", label: "ISUZU" },
      { id: "ford", label: "FORD" },
      { id: "audi", label: "AUDI" },
      { id: "jaguar", label: "JAGUAR" },
      { id: "suzuki", label: "SUZUKI" },
      { id: "toyota", label: "TOYOTA" },
      { id: "honda", label: "HONDA" },
      { id: "bmw", label: "BMW" },
      { id: "daihatsu", label: "DAIHATSU" },
      { id: "mazda", label: "MAZDA" },
      { id: "chevrolet", label: "CHEVROLET" },
      { id: "ssangyong", label: "SSANGYONG" },
      { id: "subaru", label: "SUBARU" },
      { id: "mercedes", label: "MERCEDES" },
      { id: "volvo", label: "VOLVO" },
      { id: "peugeot", label: "PEUGEOT" },
      { id: "volkswagen", label: "VOLKSWAGEN" },
      { id: "land-rover", label: "LAND ROVER" },
      { id: "lexus", label: "LEXUS" },
      { id: "mitsubishi", label: "MITSUBISHI" },
      { id: "jeep", label: "JEEP" },
      { id: "tesla", label: "TESLA" },
      { id: "ferrari", label: "FERRARI" },
      { id: "porsche", label: "PORSCHE" },
      { id: "lamborghini", label: "LAMBORGHINI" },
      { id: "bugatti", label: "BUGATTI" },
      { id: "rolls-royce", label: "ROLLS-ROYCE" },
      { id: "bentley", label: "BENTLEY" },
      { id: "citroen", label: "CITROËN" },
      { id: "renault", label: "RENAULT" },
      { id: "fiat", label: "FIAT" },
      { id: "alfa-romeo", label: "ALFA ROMEO" },
      { id: "aston-martin", label: "ASTON MARTIN" },
      { id: "infiniti", label: "INFINITI" },
      { id: "acura", label: "ACURA" },
      { id: "skoda", label: "ŠKODA" },
      { id: "seat", label: "SEAT" },
      { id: "saab", label: "SAAB" },
      { id: "chery", label: "CHERY" },
      { id: "geely", label: "GEELY" },
      { id: "mg", label: "MG" },
      { id: "haval", label: "HAVAL" },
      { id: "great-wall", label: "GREAT WALL" },
      { id: "byd", label: "BYD" },
      { id: "ram", label: "RAM" },
      { id: "lincoln", label: "LINCOLN" },
      { id: "cadillac", label: "CADILLAC" },
      { id: "maserati", label: "MASERATI" },
      { id: "pagani", label: "PAGANI" },
      { id: "koenigsegg", label: "KOENIGSEGG" },
    ],
  },
  {
    label: "Year",
    name: "year",
    componentType: "select",
    options: yearOptions,
    type: "number",
  },

  {
    label: "Transmission",
    name: "transmission",
    componentType: "select",
    options: [
      { id: "authomatic", label: "Authomatic" },
      { id: "manual", label: "Manual" },
    ],
  },

  {
    label: "Fuel-Type",
    name: "fuelType",
    componentType: "select",
    options: [
      { id: "diesel", label: "Diesel" },
      { id: "electric", label: "Electric" },
      { id: "gasoline", label: "Gasoline" },
      { id: "hybrid", label: "Hybrid" },
    ],
  },
  {
    label: "Color",
    name: "color",
    componentType: "select",
    options: [
      { id: "red", label: "Red", colorCode: "#FF0000" },
      { id: "blue", label: "Blue", colorCode: "#0000FF" },
      { id: "green", label: "Green", colorCode: "#00FF00" },
      { id: "black", label: "Black", colorCode: "#000000" },
      { id: "white", label: "White", colorCode: "#FFFFFF" },
      { id: "yellow", label: "Yellow", colorCode: "#FFFF00" },
      { id: "purple", label: "Purple", colorCode: "#800080" },
    ],
  },
];

export const rentalInfoFormControls = [
  {
    label: "Price",
    name: "price",
    min: "0",
    componentType: "input",
    type: "number",
  },

  {
    label: "Phone",
    name: "phone",
    componentType: "input",
    type: "text",
  },

  {
    label: "Available-From",
    name: "availableFrom",
    componentType: "input",
    type: "date",
  },

  {
    label: "Available-To",
    name: "availableTo",
    componentType: "input",
    type: "date",
  },

  {
    label: "Location",
    name: "location",
    componentType: "input",
    type: "text",
  },
];

export const planpayment = [
  {
    name: "Free",
  },
  {
    name: "Pro",
  },
  {
    name: "Premium",
  },
];

export const searchOptions = [
  {
    label: "Model",
    name: "model",
    componentType: "select",
    options: [
      { id: "corolla", label: "Corolla" },
      { id: "camry", label: "Camry" },
      { id: "rav4", label: "RAV4" },
      { id: "hilux", label: "Hilux" },
      { id: "civic", label: "Civic" },
      { id: "accord", label: "Accord" },
      { id: "cr-v", label: "CR-V" },
      { id: "fit", label: "Fit" },
      { id: "mustang", label: "Mustang" },
      { id: "f150", label: "F-150" },
      { id: "explorer", label: "Explorer" },
      { id: "altima", label: "Altima" },
      { id: "sentra", label: "Sentra" },
      { id: "rogue", label: "Rogue" },
      { id: "pathfinder", label: "Pathfinder" },
      { id: "tucson", label: "Tucson" },
      { id: "sonata", label: "Sonata" },
      { id: "elantra", label: "Elantra" },
      { id: "cx-5", label: "CX-5" },
      { id: "mazda3", label: "Mazda3" },
      { id: "impreza", label: "Impreza" },
      { id: "forester", label: "Forester" },
      { id: "outback", label: "Outback" },
      { id: "es350", label: "ES 350" },
      { id: "rx350", label: "RX 350" },
      { id: "lx570", label: "LX 570" },
      { id: "3-series", label: "3 Series" },
      { id: "5-series", label: "5 Series" },
      { id: "x5", label: "X5" },
      { id: "a4", label: "A4" },
      { id: "q5", label: "Q5" },
      { id: "q7", label: "Q7" },
      { id: "c-class", label: "C-Class" },
      { id: "e-class", label: "E-Class" },
      { id: "gle", label: "GLE" },
      { id: "911", label: "911" },
      { id: "cayenne", label: "Cayenne" },
      { id: "macan", label: "Macan" },
      { id: "cherokee", label: "Cherokee" },
      { id: "wrangler", label: "Wrangler" },
      { id: "compass", label: "Compass" },
      { id: "model-s", label: "Model S" },
      { id: "model-3", label: "Model 3" },
      { id: "model-x", label: "Model X" },
      { id: "model-y", label: "Model Y" },
      { id: "range-rover", label: "Range Rover" },
      { id: "defender", label: "Defender" },
      { id: "discovery", label: "Discovery" },
    ],
  },
  {
    label: "Fuel-Type",
    name: "fuelType",
    componentType: "select",
    options: [
      { id: "diesel", label: "Diesel" },
      { id: "electric", label: "Electric" },
      { id: "gasoline", label: "Gasoline" },
      { id: "hybrid", label: "Hybrid" },
    ],
  },
  {
    label: "Year",
    name: "year",
    componentType: "select",
    options: yearOptions,
    type: "number",
  },
];

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low - High" },
  { id: "price-hightolow", label: "Price: High - Low" },
  { id: "title-az", label: "Title: A to Z" },
  { id: "title-za", label: "Title: Z to A" },
];
